theme: jekyll-theme-minimal
title: jrueter's homepage
description: Bookmark this to keep an eye on my project updates!
<link rel="stylesheet" href="{{ '/assets/style.css' | https://raw.githubusercontent.com/jrueter15/jrueter15.github.io/refs/heads/main/assets/style.css }}">
